TWEAK_NAME = Doshi

$(TWEAK_NAME)_FILES = $(TWEAK_NAME).x $(wildcard ClickManager/*.m ActionExecutor/*.m)
$(TWEAK_NAME)_FRAMEWORKS = UIKit AudioToolbox AVFoundation
$(TWEAK_NAME)_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk